api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    enable_swagger_ui: true
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_enabled: true
        pagination_client_enabled: true
        pagination_items_per_page: 30
    mapping:
        paths:
            - '%kernel.project_dir%/src/Api/Resource'
            - '%kernel.project_dir%/src/Domain'
