framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            scheduler_default: 'schedule://default'
            notifications:
                dsn: '%env(REDIS_URL)%'
                options:
                    stream: notifications
            pdf_generation:
                dsn: '%env(REDIS_URL)%'
                options:
                    stream: pdf_generation
            audit:
                dsn: '%env(REDIS_URL)%'
                options:
                    stream: audit
            kpi:
                dsn: '%env(REDIS_URL)%'
                options:
                    stream: kpi

        routing:
            'App\Domain\ActivityPlanning\Message\ActivityPlanningUpdatedNotification': notifications
            'App\Domain\ActivityPlanning\Message\ActivityPlanningCreatedNotification': notifications
            'Symfony\Component\Mercure\Update': notifications
            'App\Domain\PlanPrevention\Message\GeneratePlanPreventionPdfMessage': pdf_generation
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': notifications
            'App\Domain\PermitTravail\Message\UpdateKpisMessage': kpi

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
