framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            notifications:
                dsn: '%env(REDIS_URL)%'
                options:
                    stream: notifications
            pdf_generation:
                dsn: '%env(REDIS_URL)%'
                options:
                    stream: pdf_generation
            audit:
                dsn: 'doctrine://default?queue_name=audit'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            'Symfony\Component\Mercure\Update': notifications

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
