services:
    php:
        build: ./docker/php
        container_name: toa_php
        volumes:
            - .:/var/www/toa-api
        networks:
            - toa_net
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            DATABASE_URL: postgresql://toa_user:mypasswordtoa@postgres:5432/toa_db?serverVersion=16&charset=utf8
            REDIS_URL: redis://redis:6379
            JWT_SECRET_KEY: "%kernel.project_dir%/config/jwt/private.pem"
            JWT_PUBLIC_KEY: "%kernel.project_dir%/config/jwt/public.pem"
            JWT_PASSPHRASE: aa0c378fe79f45e97fbe8dcb38cb5a663758d6bd733d0c66ca1b975cf86af284
            MERCURE_URL: http://mercure:3001/.well-known/mercure
            MERCURE_JWT_SECRET: mercure_secret
            MINIO_ENDPOINT: http://minio:9000
            MINIO_KEY: minioadmin
            MINIO_SECRET: minioadmin
            MINIO_BUCKET: toa
        healthcheck:
            test: ["CMD", "php-fpm", "-t"]
            interval: 10s
            timeout: 5s
            retries: 5

    worker_notifications:
        build: ./docker/php
        container_name: toa_worker_notifications
        command: php bin/console messenger:consume notifications --limit=500 -vv
        restart: unless-stopped
        volumes:
            - .:/var/www/toa-api
        networks:
            - toa_net
        depends_on: [php, redis]
        environment:
            DATABASE_URL: postgresql://toa_user:mypasswordtoa@postgres:5432/toa_db?serverVersion=16&charset=utf8
            REDIS_URL: redis://redis:6379
            JWT_SECRET_KEY: "%kernel.project_dir%/config/jwt/private.pem"
            JWT_PUBLIC_KEY: "%kernel.project_dir%/config/jwt/public.pem"
            JWT_PASSPHRASE: aa0c378fe79f45e97fbe8dcb38cb5a663758d6bd733d0c66ca1b975cf86af284
            MERCURE_URL: http://mercure:3001/.well-known/mercure
            MERCURE_JWT_SECRET: mercure_secret
            MINIO_ENDPOINT: http://minio:9000
            MINIO_KEY: minioadmin
            MINIO_SECRET: minioadmin
            MINIO_BUCKET: toa

    worker_pdf:
        build: ./docker/php
        container_name: toa_worker_pdf
        command: php bin/console messenger:consume pdf_generation --limit=100 -vv
        restart: unless-stopped
        volumes:
            - .:/var/www/toa-api
        networks:
            - toa_net
        depends_on: [php, redis]
        environment:
            DATABASE_URL: postgresql://toa_user:mypasswordtoa@postgres:5432/toa_db?serverVersion=16&charset=utf8
            REDIS_URL: redis://redis:6379
            JWT_SECRET_KEY: "%kernel.project_dir%/config/jwt/private.pem"
            JWT_PUBLIC_KEY: "%kernel.project_dir%/config/jwt/public.pem"
            JWT_PASSPHRASE: aa0c378fe79f45e97fbe8dcb38cb5a663758d6bd733d0c66ca1b975cf86af284
            MERCURE_URL: http://mercure:3001/.well-known/mercure
            MERCURE_JWT_SECRET: mercure_secret
            MINIO_ENDPOINT: http://minio:9000
            MINIO_KEY: minioadmin
            MINIO_SECRET: minioadmin
            MINIO_BUCKET: toa

    scheduler:
        build: ./docker/php
        container_name: toa_scheduler
        command: php bin/console messenger:consume scheduler_default --time-limit=3600 --limit=500 -vv
        restart: unless-stopped
        volumes:
            - .:/var/www/toa-api
        networks:
            - toa_net
        depends_on: [php, redis]
        environment:
            DATABASE_URL: postgresql://toa_user:mypasswordtoa@postgres:5432/toa_db?serverVersion=16&charset=utf8
            REDIS_URL: redis://redis:6379
            JWT_SECRET_KEY: "%kernel.project_dir%/config/jwt/private.pem"
            JWT_PUBLIC_KEY: "%kernel.project_dir%/config/jwt/public.pem"
            JWT_PASSPHRASE: aa0c378fe79f45e97fbe8dcb38cb5a663758d6bd733d0c66ca1b975cf86af284
            MERCURE_URL: http://mercure:3001/.well-known/mercure
            MERCURE_JWT_SECRET: mercure_secret
            MINIO_ENDPOINT: http://minio:9000
            MINIO_KEY: minioadmin
            MINIO_SECRET: minioadmin
            MINIO_BUCKET: toa

    nginx:
        image: nginx:alpine
        container_name: toa_nginx
        ports:
            - "8080:80"
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www/toa-api
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - certbot_conf:/etc/letsencrypt
            - certbot_webroot:/var/www/certbot
        depends_on:
            php:
                condition: service_healthy
        networks:
            - toa_net

    postgres:
        image: postgres:16-alpine
        container_name: toa_postgres
        environment:
            POSTGRES_DB: toa_db
            POSTGRES_USER: toa_user
            POSTGRES_PASSWORD: mypasswordtoa
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - toa_net
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U toa_user -d toa_db"]
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        image: redis:7-alpine
        container_name: toa_redis
        command: redis-server --appendonly yes
        networks:
            - toa_net

    adminer:
        image: adminer:latest
        container_name: toa_adminer
        environment:
            ADMINER_DEFAULT_SERVER: postgres
            ADMINER_DEFAULT_DRIVER: pgsql
        ports:
            - "8081:8080"
        depends_on:
            - postgres
        networks:
            - toa_net

    mercure:
        image: dunglas/mercure
        container_name: toa_mercure
        environment:
            SERVER_NAME: ":3001"
            MERCURE_PUBLISHER_JWT_KEY: mercure_secret
            MERCURE_SUBSCRIBER_JWT_KEY: mercure_secret
        ports:
            - "3001:3001"
        networks:
            - toa_net

    gotenberg:
        image: gotenberg/gotenberg:8
        container_name: toa_gotenberg
        command: gotenberg --chromium-disable-javascript=false
        ports:
            - "3002:3000"
        networks:
            - toa_net

    minio:
        image: minio/minio
        container_name: toa_minio
        command: server /data --console-address ":9001"
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - miniodata:/data
        networks:
            - toa_net

networks:
    toa_net:

volumes:
    pgdata:
    miniodata:
    certbot_conf:
    certbot_webroot:
