<?php

declare(strict_types=1);

namespace App\Domain\PermitTravail\Enum;

enum TypeDocumentPermitTravail: string
{
    case TROUSSE_SECOURS             = 'TROUSSE_SECOURS';
    case PV_SENSIBILISATION_HSE      = 'PV_SENSIBILISATION_HSE';
    case PHOTO_EPI_BASE              = 'PHOTO_EPI_BASE';
    case PV_KICKOFF_AUTORITES        = 'PV_KICKOFF_AUTORITES';
    case PV_ENVIRONNEMENT            = 'PV_ENVIRONNEMENT';
    case PHOTO_AVANCEMENT_CHANTIER   = 'PHOTO_AVANCEMENT_CHANTIER';
    case PLAN_SAUVETAGE_HAUTEUR      = 'PLAN_SAUVETAGE_HAUTEUR';
    case KIT_SAUVETAGE_HAUTEUR       = 'KIT_SAUVETAGE_HAUTEUR';
    case HARNAIS_SECURITE            = 'HARNAIS_SECURITE';
    case PIECE_IDENTITE_HABILITE     = 'PIECE_IDENTITE_HABILITE';
    case MESURE_VITESSE_VENT         = 'MESURE_VITESSE_VENT';
    case PHOTO_EPI_SPECIFIQUE        = 'PHOTO_EPI_SPECIFIQUE';
    case PHOTO_EQUIPEMENTS_ISOLANTS  = 'PHOTO_EQUIPEMENTS_ISOLANTS';
    case PV_CLOTURE_ENVIRONNEMENT    = 'PV_CLOTURE_ENVIRONNEMENT';
    case PV_FIN_TRAVAUX              = 'PV_FIN_TRAVAUX';
    case PHOTO_PROPRETE_SITE         = 'PHOTO_PROPRETE_SITE';
}
