<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Snapshot hors-ligne : ajoute updated_at sur plan_prevention/permit_travail/intervention
 * (nécessaire pour le filtre `since`) et la table tombstone_record (suppressions
 * tracées pour la sync incrémentale).
 */
final class Version20260830144012 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Snapshot hors-ligne : updated_at sur plan_prevention/permit_travail/intervention + table tombstone_record';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE "tombstone_record" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, entity_type VARCHAR(50) NOT NULL, entity_id VARCHAR(36) NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_tombstone_type_deleted_at ON "tombstone_record" (entity_type, deleted_at)');
        $this->addSql('ALTER TABLE intervention ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE permit_travail ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE plan_prevention ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE "tombstone_record"');
        $this->addSql('ALTER TABLE "intervention" DROP updated_at');
        $this->addSql('ALTER TABLE "permit_travail" DROP updated_at');
        $this->addSql('ALTER TABLE "plan_prevention" DROP updated_at');
    }
}
