<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260604122323 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "activity_planning_audit" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, field_name VARCHAR(255) NOT NULL, old_value TEXT DEFAULT NULL, new_value TEXT DEFAULT NULL, changed_by VARCHAR(255) NOT NULL, changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, planning_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9FBC91863D865311 ON "activity_planning_audit" (planning_id)');
        $this->addSql('ALTER TABLE "activity_planning_audit" ADD CONSTRAINT FK_9FBC91863D865311 FOREIGN KEY (planning_id) REFERENCES "activity_planning" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activity_planning ADD provider_email VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE activity_planning ADD status VARCHAR(50) DEFAULT \'brouillon\' NOT NULL');
        $this->addSql('ALTER TABLE activity_planning ADD permit_reference VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE activity_planning ADD permit_validated BOOLEAN NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "activity_planning_audit" DROP CONSTRAINT FK_9FBC91863D865311');
        $this->addSql('DROP TABLE "activity_planning_audit"');
        $this->addSql('ALTER TABLE "activity_planning" DROP provider_email');
        $this->addSql('ALTER TABLE "activity_planning" DROP status');
        $this->addSql('ALTER TABLE "activity_planning" DROP permit_reference');
        $this->addSql('ALTER TABLE "activity_planning" DROP permit_validated');
    }
}
