<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260618124408 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "activity_planning" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, process VARCHAR(255) NOT NULL, provider VARCHAR(255) NOT NULL, provider_email VARCHAR(255) DEFAULT NULL, project_description TEXT NOT NULL, site_code VARCHAR(255) NOT NULL, site_number VARCHAR(255) NOT NULL, site_name VARCHAR(255) NOT NULL, region VARCHAR(255) NOT NULL, theoretical_start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expected_start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expected_end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(50) NOT NULL, permit_reference VARCHAR(255) DEFAULT NULL, permit_validated BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "activity_planning_audit" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, field_name VARCHAR(255) NOT NULL, old_value TEXT DEFAULT NULL, new_value TEXT DEFAULT NULL, changed_by VARCHAR(255) NOT NULL, changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, planning_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9FBC91863D865311 ON "activity_planning_audit" (planning_id)');
        $this->addSql('CREATE TABLE "menu" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, icon VARCHAR(255) DEFAULT NULL, route VARCHAR(255) DEFAULT NULL, position INT NOT NULL, is_active BOOLEAN NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7D053A93727ACA70 ON "menu" (parent_id)');
        $this->addSql('CREATE TABLE "menu_access" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role_name VARCHAR(100) NOT NULL, can_view BOOLEAN NOT NULL, can_create BOOLEAN NOT NULL, can_edit BOOLEAN NOT NULL, can_delete BOOLEAN NOT NULL, menu_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D52E738CCCD7E912 ON "menu_access" (menu_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D52E738CCCD7E912E09C0C92 ON "menu_access" (menu_id, role_name)');
        $this->addSql('CREATE TABLE "permit" (id UUID NOT NULL, plan_prevention_id UUID DEFAULT NULL, plan_prevention_reference VARCHAR(255) DEFAULT NULL, code_site VARCHAR(100) NOT NULL, nombre_intervenants INT NOT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(50) NOT NULL, demandeur_nom VARCHAR(255) DEFAULT NULL, demandeur_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, superviseur_nom VARCHAR(255) DEFAULT NULL, superviseur_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, creer_par VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, type VARCHAR(30) NOT NULL, intitule_travaux VARCHAR(255) DEFAULT NULL, localisation VARCHAR(255) DEFAULT NULL, contractant VARCHAR(255) DEFAULT NULL, duree_max_jours INT DEFAULT NULL, travaux_risques JSON DEFAULT NULL, permis_annexes JSON DEFAULT NULL, evaluation_risques_validee BOOLEAN DEFAULT NULL, personne_competente_assignee BOOLEAN DEFAULT NULL, mesures_prevention_mises_en_place BOOLEAN DEFAULT NULL, personnel_informe BOOLEAN DEFAULT NULL, dangers_controles BOOLEAN DEFAULT NULL, type_travail JSON DEFAULT NULL, tension JSON DEFAULT NULL, type_circuit_equipement VARCHAR(255) DEFAULT NULL, description_travail TEXT DEFAULT NULL, raison_non_mise_hors_tension TEXT DEFAULT NULL, risques JSON DEFAULT NULL, materiels JSON DEFAULT NULL, mesures_prevention JSON DEFAULT NULL, secouriste_present BOOLEAN DEFAULT NULL, numeros_urgence_disponibles BOOLEAN DEFAULT NULL, engagement_demandeur BOOLEAN DEFAULT NULL, bon_consignation JSON DEFAULT NULL, prestataire VARCHAR(255) DEFAULT NULL, region VARCHAR(100) DEFAULT NULL, description_operation TEXT DEFAULT NULL, hauteur_chute VARCHAR(50) DEFAULT NULL, travail_toiture BOOLEAN DEFAULT NULL, type_pente VARCHAR(50) DEFAULT NULL, plan_sauvetage_disponible BOOLEAN DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE refresh_tokens (refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9BACE7E1C74F2195 ON refresh_tokens (refresh_token)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, name VARCHAR(255) NOT NULL, firstname VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('ALTER TABLE "activity_planning_audit" ADD CONSTRAINT FK_9FBC91863D865311 FOREIGN KEY (planning_id) REFERENCES "activity_planning" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "menu" ADD CONSTRAINT FK_7D053A93727ACA70 FOREIGN KEY (parent_id) REFERENCES "menu" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "menu_access" ADD CONSTRAINT FK_D52E738CCCD7E912 FOREIGN KEY (menu_id) REFERENCES "menu" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "activity_planning_audit" DROP CONSTRAINT FK_9FBC91863D865311');
        $this->addSql('ALTER TABLE "menu" DROP CONSTRAINT FK_7D053A93727ACA70');
        $this->addSql('ALTER TABLE "menu_access" DROP CONSTRAINT FK_D52E738CCCD7E912');
        $this->addSql('DROP TABLE "activity_planning"');
        $this->addSql('DROP TABLE "activity_planning_audit"');
        $this->addSql('DROP TABLE "menu"');
        $this->addSql('DROP TABLE "menu_access"');
        $this->addSql('DROP TABLE "permit"');
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('DROP TABLE "user"');
    }
}
