<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260604113714 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "activity_planning" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, process VARCHAR(255) NOT NULL, provider VARCHAR(255) NOT NULL, project_description TEXT NOT NULL, site_code VARCHAR(255) NOT NULL, site_number VARCHAR(255) NOT NULL, site_name VARCHAR(255) NOT NULL, region VARCHAR(255) NOT NULL, theoretical_start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expected_start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expected_end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE "activity_planning"');
    }
}
