<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260605085646 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "menu" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, icon VARCHAR(255) DEFAULT NULL, route VARCHAR(255) DEFAULT NULL, position INT NOT NULL, is_active BOOLEAN NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7D053A93727ACA70 ON "menu" (parent_id)');
        $this->addSql('CREATE TABLE "menu_access" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role_name VARCHAR(100) NOT NULL, can_view BOOLEAN NOT NULL, can_create BOOLEAN NOT NULL, can_edit BOOLEAN NOT NULL, can_delete BOOLEAN NOT NULL, menu_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D52E738CCCD7E912 ON "menu_access" (menu_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D52E738CCCD7E912E09C0C92 ON "menu_access" (menu_id, role_name)');
        $this->addSql('ALTER TABLE "menu" ADD CONSTRAINT FK_7D053A93727ACA70 FOREIGN KEY (parent_id) REFERENCES "menu" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "menu_access" ADD CONSTRAINT FK_D52E738CCCD7E912 FOREIGN KEY (menu_id) REFERENCES "menu" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activity_planning ALTER status DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "menu" DROP CONSTRAINT FK_7D053A93727ACA70');
        $this->addSql('ALTER TABLE "menu_access" DROP CONSTRAINT FK_D52E738CCCD7E912');
        $this->addSql('DROP TABLE "menu"');
        $this->addSql('DROP TABLE "menu_access"');
        $this->addSql('ALTER TABLE "activity_planning" ALTER status SET DEFAULT \'brouillon\'');
    }
}
