framework:
    messenger:
        transports:
            notifications:
                dsn: 'in-memory://'
            pdf_generation:
                dsn: 'sync://'
            kpi:
                dsn: 'sync://'
